# These are supported funding model platforms

github: Nsfr750
custom: 
  - "https://www.paypal.me/3dmega"
  - "Monero: 47Jc6MC47WJVFhiQFYwHyBNQP5BEsjUPG6tc8R37FwcTY8K5Y3LvFzveSXoGiaDQSxDrnCUBJ5WBj6Fgmsfix8VPD4w3gXF"
