# Site Settings
title: Nsfr750's Project Hub
description: Personal blog and projects by Nsfr750
tagline: Open Source Enthusiast & Developer
email: nsfr750@yandex.com
url: "https://nsfr750.github.io" # the base hostname & protocol for your site
timezone: Europe/Rome

# Setup
baseurl: ""
auxtoro: Nsfr750
laborlingvo: en # cambia nella tua lingua
ne_afisxoj: "false" # nasconde menu "tutti i post"
ne_docs: "true" # set false to disable docs menu
ne_googlesearch: "true" # nasconde menu "cerca con google"
gh_uzanto: "Nsfr750" # utente github per i commenti
#ga_tag: "G-XXXXXXXXXX" # Google Analytics tag
#ga_adsense: "ca-pub-XXXXXXXXX" # Google Adsense

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" , "??/_data", _traduko.jar]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
