# Setup
baseurl: ""
auxtoro: Nsfr750
# cambia nella tua lingua
laborlingvo: en
# rimuovi il commento dalla seguente per rimuovere il menu "tutti i post"
#ne_afisxoj: "true"
# rimuovi il commento dalla seguente riga per rimuovere il menu "cerca con google"
#ne_googlesearch: "true"
# utente github per i commenti
gh_uzanto: "Nsfr750"
# Google Analytics tag
# ga_tag: "X-XXXXXX000X"


# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" , "??/_data", _traduko.jar]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
